/**
 * ButtonController
 * Author: Neil Balaskandarajah
 * Created on: 21/03/2020
 * Versatile controller for a button component
 */

package graphics.components;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

public class ButtonController implements MouseListener {
	//Attributes
	private BoxButton button; //button to control
	private Color light; //light color
	private Color dark; //dark color
	private Runnable method; //method to run when pressed
	
	/*
	 * Can use button text as key for making path
	 */
	
	/**
	 * Create a controller for the button
	 * @param button Button to control
	 */
	public ButtonController(BoxButton button, Runnable method) {
		//set attributes
		this.button = button;
		this.method = method;
	} //end constructor

	/**
	 * Set the colors to be used in the button
	 * @param light Light color for when the button isn't entered
	 * @param dark Dark color for when the button is entered
	 */
	public void setColors(Color light, Color dark) {
		this.light = light;
		this.dark = dark;
		
		button.setBackgroundColor(light);
	} //end setColors
	
	/**
	 * Change the color to dark when the mouse enters
	 * @param m MouseEvent generated by interface
	 */
	public void mouseEntered(MouseEvent m) {
		if (!button.isLocked()) {
			button.setBackgroundColor(dark);
		} //if
	} //end mouseEntered

	/**
	 * Change the color to light when the mouse leaves
	 * @param m MouseEvent generated by interface
	 */
	public void mouseExited(MouseEvent m) {
		if (!button.isLocked()) {
			button.setBackgroundColor(light);
		} //if
	} //end mouseExited

	/**
	 * Change the color to a darker dark when the mouse ispressed
	 * @param m MouseEvent generated by interface
	 */
	public void mousePressed(MouseEvent m) {
		if (!button.isLocked()) {
			button.setBackgroundColor(dark.darker());
		} //if
		
		method.run();
	} //end mousePressed

	/**
	 * Change the color back to light when the mouse is releaed
	 * @param m MouseEvent generated by interface
	 */
	public void mouseReleased(MouseEvent m) {
		if (!button.isLocked()) {
			button.setBackgroundColor(dark);
		} //if
	} //end mouseReleased
	
	/*
	 * Unimplemented
	 */
	public void mouseClicked(MouseEvent m) {}
} //end class
